from .config_loader import load_config
from .logger import Logger
from .pipeline import DedupPipeline
from .sink import ISink, LoggingSink, PostgresSink, create_sink
from .types import (
    BlockingConfig,
    BlockingStrategy,
    ClassifierConfig,
    ClassifierType,
    ComparableField,
    ComparisonFieldConfig,
    ComparisonVector,
    CandidatePair,
    DeduplicationError,
    DeduplicationRequest,
    DeduplicationResult,
    DedupDecision,
    DedupStatus,
    DuplicateCluster,
    FieldScore,
    JobPostingRecord,
    PipelineConfig,
    PipelineErrorCode,
    PipelineStats,
    ProcessedRecord,
    SimilarityMetric,
)

__all__ = [
    "DedupPipeline",
    "Logger",
    "load_config",
    "ISink",
    "LoggingSink",
    "PostgresSink",
    "create_sink",
    "BlockingConfig",
    "BlockingStrategy",
    "CandidatePair",
    "ClassifierConfig",
    "ClassifierType",
    "ComparableField",
    "ComparisonFieldConfig",
    "ComparisonVector",
    "DeduplicationError",
    "DeduplicationRequest",
    "DeduplicationResult",
    "DedupDecision",
    "DedupStatus",
    "DuplicateCluster",
    "FieldScore",
    "JobPostingRecord",
    "PipelineConfig",
    "PipelineErrorCode",
    "PipelineStats",
    "ProcessedRecord",
    "SimilarityMetric",
]
